// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhFvCvUKU41-0AMaRTsz3uA6xhYmclFQ',
    appId: '1:62253446347:web:ce5bc227d80e5df395574e',
    messagingSenderId: '62253446347',
    projectId: 'naildeliveries-d1335',
    authDomain: 'naildeliveries-d1335.firebaseapp.com',
    storageBucket: 'naildeliveries-d1335.appspot.com',
    measurementId: 'G-SBPVC5NCEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz-wJvX_LjJKfJ36Qv_dr-CSOknEu7wKw',
    appId: '1:62253446347:android:1bcd6496f9690d4e95574e',
    messagingSenderId: '62253446347',
    projectId: 'naildeliveries-d1335',
    storageBucket: 'naildeliveries-d1335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq58XVdt-4c1ffyO_ORi5vY9d_MfjYvtU',
    appId: '1:62253446347:ios:86c26ad4eadaaef595574e',
    messagingSenderId: '62253446347',
    projectId: 'naildeliveries-d1335',
    storageBucket: 'naildeliveries-d1335.appspot.com',
    iosClientId: '62253446347-vjbn2qc8mcrupjfikp3ihrri504g5q1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.nialDeliveries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq58XVdt-4c1ffyO_ORi5vY9d_MfjYvtU',
    appId: '1:62253446347:ios:91368842da6ed40c95574e',
    messagingSenderId: '62253446347',
    projectId: 'naildeliveries-d1335',
    storageBucket: 'naildeliveries-d1335.appspot.com',
    iosClientId: '62253446347-vlsir1n0m17q6vif0rs9763660pt17h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nialDeliveries.RunnerTests',
  );
}
